### ISSUE TITLE
URL Field: is this a valid field type?

### ISSUE THREAD

**Issue by claytoncollie** [wpmetabox/library#1]
https://github.com/wpmetabox/library/blob/3ebe1f0558ee77c1202113af31b71ad264e85c08/fields/url.php#L10

I installed rilwis/meta-box ^4.19 via Composer and cannot find the URL field inside the /inc/ folder. But I found this snippet and can use the URL field just fine. Am I missing something here? I would think since the url field is not in my package that I should not be able to declare the url field type.

See the admin code below.  Looks like it is declaring the field properly, I'm just not sure HOW it is doing that when the /inc/url.php does not exist.

![image](https://user-images.githubusercontent.com/4236538/41921783-41aad03e-7929-11e8-9965-a25db237af04.png)

**Comment by rilwis** [comment]
Hi,

Meta Box supports all HTML input types. `url` is one of them. There's no specific PHP class for it.

See [this documentation](https://docs.metabox.io/html5-input-types/) for more info.
