### ISSUE TITLE
composer mb-relationships installer-paths package name  does not match actual package name

### ISSUE THREAD

**Issue by wkoehn** [wpmetabox/library#6]
https://github.com/wpmetabox/library/blob/master/composer/composer.json

The actual package name: "wpackagist-plugin/mb-relationships": "^1.3" does not match the package name listed in installer-paths: "vendor/meta-box/mb-relationships": ["wpackagist-plugin/mb-relation"].

This causes the extension to be placed into the default wp-content directory instead of correctly placed under /vendor/meta-box.

**Comment by rilwis** [comment]
Fixed in https://github.com/wpmetabox/library/commit/fb5898f46db7b2ec7691380e323e5929d31601e4
