### ISSUE TITLE
Is this file up to date as of August 2020?

### ISSUE THREAD

**Issue by claytoncollie** [wpmetabox/library#8]
https://github.com/wpmetabox/library/blob/87a47640ccfbaf9ab71c83bd0f45eaaccf72ab0b/general/demo.php#L1

I am adding support for Metabox fields inside the WordPress Simple History plugin and was looking for a pre-configured list of all MB fields. This looks great, but want to confirm that it is the latest and greatest. Is this how you all troubleshoot fields and third-party support on your end?

**Comment by rilwis** [comment]
Hi @claytoncollie ,

Yes, this file is still working as expected. It's quite old, but we don't have any breaking changes. So, everything is fine.
